### ISSUE TITLE
Combine 'deploy' and 'exporter' charts into a single pelorus chart that deploys the full stack.

### ISSUE THREAD

**Issue by etsauer** [redhat-cop/pelorus#125]
I'm thinking the structure of a values file that looks something like:

```
---
global:
  deployment:
    labels:
      app.kubernetes.io/component: prometheus
      app.kubernetes.io/name: pelorus
      app.kubernetes.io/version: v0.33.0
  # custom_ca: true
  extra_prometheus_hosts:

exporters:
  comittime:
    app_name: deploytime-exporter
    # env_from_secrets:
    # - github-secret
    # extraEnv:
    # - name: APP_LABEL
    #   value: foo
    source_context_dir: exporters/committime
    source_ref: master
    source_url: https://github.com/redhat-cop/pelorus.git
    scrapeInterval: 5m
  deploytime:
    ...
  failure:
```
